// Code generated by wit-bindgen-go. DO NOT EDIT.

package context

import (
	"go.bytecodealliance.org/cm"
)

func lower_AttributeValue(v AttributeValue) (f0 uint32, f1 *uint8, f2 uint32) {
	f0 = (uint32)(v.Tag())
	switch f0 {
	case 0: // string
		v1, v2 := cm.LowerString(*cm.Case[string](&v, 0))
		f1 = (*uint8)(v1)
		f2 = (uint32)(v2)
	}
	return
}
