// Code generated by wit-bindgen-go. DO NOT EDIT.

package context

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "golem:api@1.1.6".

//go:wasmimport golem:api/context@1.1.6 [resource-drop]span
//go:noescape
func wasmimport_SpanResourceDrop(self0 uint32)

//go:wasmimport golem:api/context@1.1.6 [method]span.finish
//go:noescape
func wasmimport_SpanFinish(self0 uint32)

//go:wasmimport golem:api/context@1.1.6 [method]span.set-attribute
//go:noescape
func wasmimport_SpanSetAttribute(self0 uint32, name0 *uint8, name1 uint32, value0 uint32, value1 *uint8, value2 uint32)

//go:wasmimport golem:api/context@1.1.6 [method]span.set-attributes
//go:noescape
func wasmimport_SpanSetAttributes(self0 uint32, attributes0 *Attribute, attributes1 uint32)

//go:wasmimport golem:api/context@1.1.6 [method]span.started-at
//go:noescape
func wasmimport_SpanStartedAt(self0 uint32, result *DateTime)

//go:wasmimport golem:api/context@1.1.6 [resource-drop]invocation-context
//go:noescape
func wasmimport_InvocationContextResourceDrop(self0 uint32)

//go:wasmimport golem:api/context@1.1.6 [method]invocation-context.get-attribute
//go:noescape
func wasmimport_InvocationContextGetAttribute(self0 uint32, key0 *uint8, key1 uint32, inherited0 uint32, result *cm.Option[AttributeValue])

//go:wasmimport golem:api/context@1.1.6 [method]invocation-context.get-attribute-chain
//go:noescape
func wasmimport_InvocationContextGetAttributeChain(self0 uint32, key0 *uint8, key1 uint32, result *cm.List[AttributeValue])

//go:wasmimport golem:api/context@1.1.6 [method]invocation-context.get-attribute-chains
//go:noescape
func wasmimport_InvocationContextGetAttributeChains(self0 uint32, result *cm.List[AttributeChain])

//go:wasmimport golem:api/context@1.1.6 [method]invocation-context.get-attributes
//go:noescape
func wasmimport_InvocationContextGetAttributes(self0 uint32, inherited0 uint32, result *cm.List[Attribute])

//go:wasmimport golem:api/context@1.1.6 [method]invocation-context.parent
//go:noescape
func wasmimport_InvocationContextParent(self0 uint32, result *cm.Option[InvocationContext])

//go:wasmimport golem:api/context@1.1.6 [method]invocation-context.span-id
//go:noescape
func wasmimport_InvocationContextSpanID(self0 uint32, result *SpanID)

//go:wasmimport golem:api/context@1.1.6 [method]invocation-context.trace-context-headers
//go:noescape
func wasmimport_InvocationContextTraceContextHeaders(self0 uint32, result *cm.List[[2]string])

//go:wasmimport golem:api/context@1.1.6 [method]invocation-context.trace-id
//go:noescape
func wasmimport_InvocationContextTraceID(self0 uint32, result *TraceID)

//go:wasmimport golem:api/context@1.1.6 start-span
//go:noescape
func wasmimport_StartSpan(name0 *uint8, name1 uint32) (result0 uint32)

//go:wasmimport golem:api/context@1.1.6 current-context
//go:noescape
func wasmimport_CurrentContext() (result0 uint32)

//go:wasmimport golem:api/context@1.1.6 allow-forwarding-trace-context-headers
//go:noescape
func wasmimport_AllowForwardingTraceContextHeaders(allow0 uint32) (result0 uint32)
