// Code generated by wit-bindgen-go. DO NOT EDIT.

package container

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// ContainerMetadataShape is used for storage in variant or result types.
type ContainerMetadataShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(ContainerMetadata{})]byte
}

// ObjectMetadataShape is used for storage in variant or result types.
type ObjectMetadataShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(ObjectMetadata{})]byte
}

// TupleListObjectNameBoolShape is used for storage in variant or result types.
type TupleListObjectNameBoolShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Tuple[cm.List[ObjectName], bool]{})]byte
}

// TupleU64BoolShape is used for storage in variant or result types.
type TupleU64BoolShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Tuple[uint64, bool]{})]byte
}
