// Code generated by wit-bindgen-go. DO NOT EDIT.

package host

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "golem:api@1.1.6".

//go:wasmimport golem:api/host@1.1.6 [resource-drop]get-workers
//go:noescape
func wasmimport_GetWorkersResourceDrop(self0 uint32)

//go:wasmimport golem:api/host@1.1.6 [constructor]get-workers
//go:noescape
func wasmimport_NewGetWorkers(componentId0 uint64, componentId1 uint64, filter0 uint32, filter1 *WorkerAllFilter, filter2 uint32, precise0 uint32) (result0 uint32)

//go:wasmimport golem:api/host@1.1.6 [method]get-workers.get-next
//go:noescape
func wasmimport_GetWorkersGetNext(self0 uint32, result *cm.Option[cm.List[WorkerMetadata]])

//go:wasmimport golem:api/host@1.1.6 create-promise
//go:noescape
func wasmimport_CreatePromise(result *PromiseID)

//go:wasmimport golem:api/host@1.1.6 await-promise
//go:noescape
func wasmimport_AwaitPromise(promiseId0 uint64, promiseId1 uint64, promiseId2 *uint8, promiseId3 uint32, promiseId4 uint64, result *cm.List[uint8])

//go:wasmimport golem:api/host@1.1.6 poll-promise
//go:noescape
func wasmimport_PollPromise(promiseId0 uint64, promiseId1 uint64, promiseId2 *uint8, promiseId3 uint32, promiseId4 uint64, result *cm.Option[cm.List[uint8]])

//go:wasmimport golem:api/host@1.1.6 complete-promise
//go:noescape
func wasmimport_CompletePromise(promiseId0 uint64, promiseId1 uint64, promiseId2 *uint8, promiseId3 uint32, promiseId4 uint64, data0 *uint8, data1 uint32) (result0 uint32)

//go:wasmimport golem:api/host@1.1.6 delete-promise
//go:noescape
func wasmimport_DeletePromise(promiseId0 uint64, promiseId1 uint64, promiseId2 *uint8, promiseId3 uint32, promiseId4 uint64)

//go:wasmimport golem:api/host@1.1.6 get-oplog-index
//go:noescape
func wasmimport_GetOplogIndex() (result0 uint64)

//go:wasmimport golem:api/host@1.1.6 set-oplog-index
//go:noescape
func wasmimport_SetOplogIndex(oplogIdx0 uint64)

//go:wasmimport golem:api/host@1.1.6 oplog-commit
//go:noescape
func wasmimport_OplogCommit(replicas0 uint32)

//go:wasmimport golem:api/host@1.1.6 mark-begin-operation
//go:noescape
func wasmimport_MarkBeginOperation() (result0 uint64)

//go:wasmimport golem:api/host@1.1.6 mark-end-operation
//go:noescape
func wasmimport_MarkEndOperation(begin0 uint64)

//go:wasmimport golem:api/host@1.1.6 get-retry-policy
//go:noescape
func wasmimport_GetRetryPolicy(result *RetryPolicy)

//go:wasmimport golem:api/host@1.1.6 set-retry-policy
//go:noescape
func wasmimport_SetRetryPolicy(newRetryPolicy0 uint32, newRetryPolicy1 uint64, newRetryPolicy2 uint64, newRetryPolicy3 float64, newRetryPolicy4 uint32, newRetryPolicy5 float64)

//go:wasmimport golem:api/host@1.1.6 get-oplog-persistence-level
//go:noescape
func wasmimport_GetOplogPersistenceLevel() (result0 uint32)

//go:wasmimport golem:api/host@1.1.6 set-oplog-persistence-level
//go:noescape
func wasmimport_SetOplogPersistenceLevel(newPersistenceLevel0 uint32)

//go:wasmimport golem:api/host@1.1.6 get-idempotence-mode
//go:noescape
func wasmimport_GetIdempotenceMode() (result0 uint32)

//go:wasmimport golem:api/host@1.1.6 set-idempotence-mode
//go:noescape
func wasmimport_SetIdempotenceMode(idempotent0 uint32)

//go:wasmimport golem:api/host@1.1.6 generate-idempotency-key
//go:noescape
func wasmimport_GenerateIdempotencyKey(result *UUID)

//go:wasmimport golem:api/host@1.1.6 update-worker
//go:noescape
func wasmimport_UpdateWorker(workerId0 uint64, workerId1 uint64, workerId2 *uint8, workerId3 uint32, targetVersion0 uint64, mode0 uint32)

//go:wasmimport golem:api/host@1.1.6 get-self-metadata
//go:noescape
func wasmimport_GetSelfMetadata(result *WorkerMetadata)

//go:wasmimport golem:api/host@1.1.6 get-worker-metadata
//go:noescape
func wasmimport_GetWorkerMetadata(workerId0 uint64, workerId1 uint64, workerId2 *uint8, workerId3 uint32, result *cm.Option[WorkerMetadata])

//go:wasmimport golem:api/host@1.1.6 fork-worker
//go:noescape
func wasmimport_ForkWorker(sourceWorkerId0 uint64, sourceWorkerId1 uint64, sourceWorkerId2 *uint8, sourceWorkerId3 uint32, targetWorkerId0 uint64, targetWorkerId1 uint64, targetWorkerId2 *uint8, targetWorkerId3 uint32, oplogIdxCutOff0 uint64)

//go:wasmimport golem:api/host@1.1.6 revert-worker
//go:noescape
func wasmimport_RevertWorker(workerId0 uint64, workerId1 uint64, workerId2 *uint8, workerId3 uint32, revertTarget0 uint32, revertTarget1 uint64)

//go:wasmimport golem:api/host@1.1.6 resolve-component-id
//go:noescape
func wasmimport_ResolveComponentID(componentReference0 *uint8, componentReference1 uint32, result *cm.Option[ComponentID])

//go:wasmimport golem:api/host@1.1.6 resolve-worker-id
//go:noescape
func wasmimport_ResolveWorkerID(componentReference0 *uint8, componentReference1 uint32, workerName0 *uint8, workerName1 uint32, result *cm.Option[WorkerID])

//go:wasmimport golem:api/host@1.1.6 resolve-worker-id-strict
//go:noescape
func wasmimport_ResolveWorkerIDStrict(componentReference0 *uint8, componentReference1 uint32, workerName0 *uint8, workerName1 uint32, result *cm.Option[WorkerID])

//go:wasmimport golem:api/host@1.1.6 fork
//go:noescape
func wasmimport_Fork(newName0 *uint8, newName1 uint32) (result0 uint32)
