// Code generated by wit-bindgen-go. DO NOT EDIT.

package blobstore

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasi:blobstore".

//go:wasmimport wasi:blobstore/blobstore create-container
//go:noescape
func wasmimport_CreateContainer(name0 *uint8, name1 uint32, result *cm.Result[string, Container, Error])

//go:wasmimport wasi:blobstore/blobstore get-container
//go:noescape
func wasmimport_GetContainer(name0 *uint8, name1 uint32, result *cm.Result[string, Container, Error])

//go:wasmimport wasi:blobstore/blobstore delete-container
//go:noescape
func wasmimport_DeleteContainer(name0 *uint8, name1 uint32, result *cm.Result[Error, struct{}, Error])

//go:wasmimport wasi:blobstore/blobstore container-exists
//go:noescape
func wasmimport_ContainerExists(name0 *uint8, name1 uint32, result *cm.Result[string, bool, Error])

//go:wasmimport wasi:blobstore/blobstore copy-object
//go:noescape
func wasmimport_CopyObject(src0 *uint8, src1 uint32, src2 *uint8, src3 uint32, dest0 *uint8, dest1 uint32, dest2 *uint8, dest3 uint32, result *cm.Result[Error, struct{}, Error])

//go:wasmimport wasi:blobstore/blobstore move-object
//go:noescape
func wasmimport_MoveObject(src0 *uint8, src1 uint32, src2 *uint8, src3 uint32, dest0 *uint8, dest1 uint32, dest2 *uint8, dest3 uint32, result *cm.Result[Error, struct{}, Error])
